name: 'Wait For Check'
description: 'Wait for another GitHub check to complete'
author: 'Deepinsight'
branding:
  icon: 'check-circle'
  color: 'green'
inputs:
  token:
    description: 'The GitHub token to use for making API requests.'
    required: true
  checkName:
    description: |
      The name of the GitHub check/workflow to wait for. For example, `build` or `deploy`. Either this xor "workflowName" must be provided.
      It can also be a list of check names, in the form of a newline-separated list.
  workflowName:
    description: |
       The name of the GitHub workflow to wait for. For example, `build` or `deploy`. Either this xor "checkName" must be provided.
       It can also be a list of workflow names, in the form of a newline-separated list or comma-separated list between square brackets.
  ref:
    description: |
      The Git ref of the commit you want to poll for a passing check/workflow.
      By default the PR head if present; otherwise the current sha.
  successConclusions:
    description: |
      A list of conlusions of the check/workflow run that will result in this action run succeeding.
      Possible options are: 
          success|failure|neutral|cancelled|skipped|timed_out|action_required|not_found
    default: "success|skipped|not_found"
  repo:
    description: 'The name of the GitHub repository you want to poll for a passing check/workflow.'
  owner:
    description: 'The owner of the GitHub repository you want to poll for a passing check/workflow.'
  timeoutSeconds:
    description: 'The number of seconds to wait for per check/workflow to complete.'
    default: '600'
  intervalSeconds:
    description: 'The number of seconds to wait before each poll of the GitHub API.'
    default: '10'
  warmupSeconds:
    description: 'The number of seconds to poll until a check/workflow should be found'
    default: '0'
  cancelOnFailure:
    description: If true, when the conclusion isn't any of the `successConclusions`, the current workflow is cancelled instead of failed.
    default: false
runs:
  using: 'node20'
  main: 'dist/index.js'
