name: 'Wait For Check'
description: 'Wait for another GitHub check to complete'
author: 'Deepinsight'
branding:
  icon: 'check-circle'
  color: 'green'
inputs:
  token:
    description: 'The GitHub token to use for making API requests.'
    required: true
  checkName:
    description: 'The name of the GitHub check to wait for. For example, `build` or `deploy`. Either this xor "workflowName" must be provided.'
  workflowName:
    description: 'The name of the GitHub workflow to wait for. For example, `build` or `deploy`. Either this xor "checkName" must be provided.'
  ref:
    description: |
      The Git ref of the commit you want to poll for a passing check.
      By default the PR head if present; otherwise the current sha.
  repo:
    description: 'The name of the GitHub repository you want to poll for a passing check.'
  owner:
    description: 'The owner of the GitHub repository you want to poll for a passing check.'
  timeoutSeconds:
    description: 'The number of seconds to wait for the check to complete.'
    default: '600'
  intervalSeconds:
    description: 'The number of seconds to wait before each poll of the GitHub API.'
    default: '10'
  warmupSeconds:
    description: 'The number of seconds to poll until a check should be found'
    default: '10'
runs:
  using: 'node16'
  main: 'dist/index.js'
