name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master
      - "releases/*"

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: node --version; npm --version
      - name: npm install
        run: npm ci
      
      - run: npm run all

  integration-test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: build
          successConclusions: success
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Also do an integration test run with anyOf(...)
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: build
          successConclusions: anyOf(success)
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

  ensure-npm-ran-pack: # make sure the js is compiled
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Back up current compiled js
        run: mv dist/index.js dist/index.current.js

      - name: npm install
        run: npm ci

      - name: pack
        run: npm run build && npm run pack

      - name: ensure `npm run pack` was ran and committed
        run: |
          diff dist/index.js dist/index.current.js \
               --ignore-space-change               \
               --ignore-blank-lines                \
               --strip-trailing-cr
